name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening an issue! Known issues are often ignored until it is merged with the original issue, please check to see if your issue is new/unique to speed up the process'
        pr-message: 'Thank you for opening a pull request! You can label the PR [FIX] if you are fixing an issue.'
